### PR TITLE
Problems compiling and installing this driver on Kali Nethunter.

### PR DESCRIPTION
**Pull request by s01hip-e**
Hello, I didn’t know where to write, so I wrote here. Please help me with compiling and installing this driver. I am using Nexus 5 Marshmallow, the official version of Kali Nethunter 2019.4. And the tp-link tl-wn722n v3 wireless adapter, it has an rtl8188eus chipset. I acted on this instruction BUILD_FOR_NETHUNTER.md. "make" returns an error (Screenshot), compilation does not succeed. It seems to me that I don’t have most of the dependent packages and there are errors with SymLink (Screenshot). I can’t solve this problem for about a week now.
Screenshot_20200121-191943

### CODE REVIEW

**Comment by kimocoder** [comment]
You don't have kernel headers or anything

**Comment by imag1nator** [comment]
Hello, please help me, i have leeco le2, Android 6 with kali netHunter and kernel AndromodX from this repository https://github.com/rohitjaiswal/AndroModX-s2/

When i try to run command make module_prepare, i will have an make error 2.

I tried to compile driver for this kernel on pc, then i get a lot of error.

How can I get .ko file?

**Comment by imag1nator** [comment]
There is not headers for kali net hunter

**Comment by egor21-dev** [comment]
> There is not headers for kali net hunter

Yes, I'm have this problem too. For Kali NetHunter don't have kernel headers and kernel source, and kernel headers for Kali Linux don't fit for NetHunter. Need find kernel source for only your device and make headers from her. And need have toolchain compiler, files .ko need make as kernel modules and execute "insmod name_driver.ko". But it's in theory, on practice I'm could not do it.

**Comment by aircrack-ng** [comment]
@imag1nator @egor21-dev please use Aircrack-ng forum, there is a dedicated section where you can ask questions like this. You're asking something different than what the original issue was (which has been solved). If your question turns out there is a BUG here, feel free to open a new ticket with details, otherwise, it should stay in the forum.

@imag1nator Just FYI, saying there is a "make error 2" doesn't help finding what the problem is, a full compilation log is required (in the forum) with as much details as possible (cross compiler used, toolchain, etc).

Thank you

**Comment by kimocoder** [comment]
Drivers has to be compiled within the kernel sources.
We've made a tool for doing this automaticly, I'll get back to that soon.

**Comment by BeingDatta** [comment]
> Drivers has to be compiled within the kernel sources.
> We've made a tool for doing this automaticly, I'll get back to that soon.

Hey @kimocoder  can you elaborate what do you mean by kernel source ???
1. my linux kernel source
2. my android kernel source
3. my nethunter kernel source (which as discussed above is not present inside /lib/modules/kernel version/build or  /lib/modules/kernel version/source).

Regards.

**Pull request closed without merging**
